import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Brain, Sun, Moon, Clock, Battery, Eye, Heart, Coffee, Wind, Zap, Sparkles } from 'lucide-react';

function DigitalWellbeing() {
  // In a real app, these would be generated by an AI model
  const dailyTips = [
    {
      category: "Morning Routine",
      icon: <Sun className="w-6 h-6 text-teal-400" />,
      tips: [
        "Start your day with 10 minutes of mindful breathing before checking devices",
        "Use warm, natural light instead of blue light during early hours",
        "Set positive digital intentions for the day"
      ]
    },
    {
      category: "Work-Life Balance",
      icon: <Battery className="w-6 h-6 text-teal-400" />,
      tips: [
        "Take a 5-minute nature break for every 25 minutes of screen time",
        "Use focus mode during deep work sessions",
        "Practice mindful email checking - schedule specific times"
      ]
    },
    {
      category: "Digital Mindfulness",
      icon: <Brain className="w-6 h-6 text-teal-400" />,
      tips: [
        "Enable grayscale mode during leisure browsing",
        "Practice conscious app opening - ask 'why' before each use",
        "Set app-specific time limits based on your energy levels"
      ]
    },
    {
      category: "Evening Wellness",
      icon: <Moon className="w-6 h-6 text-teal-400" />,
      tips: [
        "Activate blue light filters 2 hours before bedtime",
        "Create a digital sunset routine",
        "Practice gratitude journaling away from devices"
      ]
    }
  ];

  const wellnessStats = [
    {
      icon: <Clock className="w-8 h-8 text-teal-400" />,
      stat: "2.5 hrs",
      label: "Recommended max social media time"
    },
    {
      icon: <Eye className="w-8 h-8 text-teal-400" />,
      stat: "20-20-20",
      label: "Eye care rule (20s break every 20min)"
    },
    {
      icon: <Heart className="w-8 h-8 text-teal-400" />,
      stat: "85%",
      label: "Users report better sleep with digital limits"
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-900 to-indigo-900">
      <div className="container mx-auto px-4 py-8">
        <Link 
          to="/peace" 
          className="inline-flex items-center text-teal-400 hover:text-teal-300 mb-8 transition-colors"
        >
          <ArrowLeft className="w-5 h-5 mr-2" />
          Back to Support
        </Link>

        <div className="max-w-4xl mx-auto">
          <div className="bg-slate-800/50 backdrop-blur-sm p-8 rounded-xl animate-fadeIn">
            {/* Header */}
            <div className="text-center mb-12">
              <div className="flex items-center justify-center mb-4">
                <Sparkles className="w-10 h-10 text-teal-400 mr-3 animate-pulse" />
                <h1 className="text-3xl font-bold text-white">AI-Powered Digital Well-being Tips</h1>
              </div>
              <p className="text-gray-300 max-w-2xl mx-auto">
                Personalized recommendations powered by AI to help you maintain a healthy relationship with technology.
                These tips are dynamically generated based on current research and user patterns.
              </p>
            </div>

            {/* Wellness Stats */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-12">
              {wellnessStats.map((stat, index) => (
                <div key={index} className="bg-slate-700/50 p-6 rounded-lg text-center transform hover:scale-105 transition-transform">
                  <div className="flex justify-center mb-3">{stat.icon}</div>
                  <div className="text-2xl font-bold text-teal-400 mb-1">{stat.stat}</div>
                  <div className="text-gray-300 text-sm">{stat.label}</div>
                </div>
              ))}
            </div>

            {/* Daily Tips */}
            <div className="space-y-6">
              {dailyTips.map((section, index) => (
                <div key={index} className="bg-slate-700/30 p-6 rounded-lg animate-fadeInUp" style={{ animationDelay: `${index * 0.1}s` }}>
                  <div className="flex items-center mb-4">
                    {section.icon}
                    <h2 className="text-xl font-semibold text-white ml-3">{section.category}</h2>
                  </div>
                  <ul className="space-y-3">
                    {section.tips.map((tip, tipIndex) => (
                      <li key={tipIndex} className="flex items-start text-gray-300">
                        <Zap className="w-5 h-5 text-teal-400 mr-3 flex-shrink-0 mt-1" />
                        <span>{tip}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>

            {/* Personalized Insight */}
            <div className="mt-12 bg-gradient-to-r from-teal-500/20 to-emerald-500/20 p-6 rounded-lg">
              <div className="flex items-center justify-between">
                <div className="space-y-2">
                  <h2 className="text-xl font-semibold text-white flex items-center">
                    <Coffee className="w-5 h-5 mr-2" />
                    Today's Wellness Focus
                  </h2>
                  <p className="text-gray-300">
                    Focus on mindful technology use during your peak energy hours (10 AM - 2 PM)
                  </p>
                </div>
                <Wind className="w-8 h-8 text-teal-400 animate-float" />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default DigitalWellbeing;